### ISSUE TITLE
Integrar GitHub y Taiga

### ISSUE THREAD

**Issue by greenled** [thunderbit/thunderbit#1]
Este ticket debería ser visible en https://tree.taiga.io/project/greenled-thunderbit-1

**Comment by greenled** [comment]
Se ve, pero no tengo cómo actualizarlo/cerrarlo desde Taiga :(

**Comment by greenled** [comment]
Habrá que esperar a que implementen esa funcionalidad.

**Comment by rickmclean** [comment]
Lo veo desde GitHub. Voy a ver si esto también se ve en Taiga.

**Comment by greenled** [comment]
Nada, que hay que esperar a una mejor integración. Gestionemos los tickets de código en GitHub y los del resto de las actividades en Taiga. Más adelante probamos nuevamente.
